In [1]:
import json
import pandas as pd

path_json = '/home/timssh/ML/TAGGING/DATA/datasets/tits_size.json'
list_path = '/home/timssh/ML/TAGGING/DATA/datasets/bad_lists/tits_size.txt'

with open(path_json) as f:
    json_ = json.load(f)

json_.keys()

dict_keys(['cat', 'num2label', 'weights', 'data'])

In [2]:
df = pd.read_json(json_["data"])
df

,path,big tits,flat chested,huge tits,small tits
0,5256efc443397c52eb34d4aaa60c497a.jpeg,1,0,0,0
1,38ee69c1fe57632e81513f88ce68d652.jpg,1,0,0,0
2,3f8fec47b8572f31187e328ab7fdf629.jpeg,1,0,0,0
3,7afd109fa81489e83e2114c5cdceaa00.jpeg,1,0,0,0
4,7bcac70602da1ca18f8b855fe71c1bb6.jpeg,1,0,0,0
...,...,...,...,...,...
23455,0af92e678dedd29db263ee339e22fcfc.jpeg,0,0,0,0
23456,513c7b76f111a46cdff3d0ab2fb6c56e.jpeg,0,0,0,0
23457,029c6997a7406605552dbec7f668b728.jpeg,0,0,0,0
23458,3cb95b790af3f46716c58f0196f230f1.jpeg,0,0,0,0
23459,b06aa43f58fe94a74eac37a2b1cd42d4.jpeg,0,0,0,0

In [3]:
with open(list_path) as f:
    bad_list = f.read()
bad_list = list(bad_list.split('\n'))

df = df[~df['path'].isin(bad_list)]
df = df.reset_index(drop=True)
df

,path,big tits,flat chested,huge tits,small tits
0,5256efc443397c52eb34d4aaa60c497a.jpeg,1,0,0,0
1,3f8fec47b8572f31187e328ab7fdf629.jpeg,1,0,0,0
2,7afd109fa81489e83e2114c5cdceaa00.jpeg,1,0,0,0
3,7bcac70602da1ca18f8b855fe71c1bb6.jpeg,1,0,0,0
4,35caadc71782c0d8a1d54618adc60a59.jpeg,1,0,0,0
...,...,...,...,...,...
22953,0af92e678dedd29db263ee339e22fcfc.jpeg,0,0,0,0
22954,513c7b76f111a46cdff3d0ab2fb6c56e.jpeg,0,0,0,0
22955,029c6997a7406605552dbec7f668b728.jpeg,0,0,0,0
22956,3cb95b790af3f46716c58f0196f230f1.jpeg,0,0,0,0
22957,b06aa43f58fe94a74eac37a2b1cd42d4.jpeg,0,0,0,0

In [4]:
json_['data'] = df.to_json()
with open(path_json, "w") as f:
    f.write(json.dumps(json_))